[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  VITE_API_BASE = "https://prepdash.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
